### ISSUE TITLE
Only css files are monitored

### ISSUE THREAD

**Issue by hongrich** [darwin/xrefresh-server#3]
Thanks to Steve Hull for using directory watcher for xrefresh-server so it would work on other platforms. But after those changes, xrefresh-server now ignores file/dir_include/exclue filters. Moreover, it now only monitors .css files

Looking at the code, this seem to be hardcoded into monitor.rb at line 13

**Comment by darwin** [comment]
Perfect. Thanks for you contribution. I wanted to do it myself, but then just reverted few commits back because I have no problems with RubyCocoa on my machine.

Your code is merged here: http://github.com/darwin/xrefresh-server/commit/3706261
